### ISSUE TITLE
PartyClose fails to deserialize

### ISSUE THREAD

**Issue by jasonwinterpixel** [heroiclabs/nakama-godot#104]
When a client receives a PartyClose it fails to deserialize because it does not have an `_init()` that takes no arguments. All other types in NakamAPI.gd and NakamaRTAPI.gd have a `_init()` of the form:

```
func _init(p_ex = null).(p_ex):
	pass
```

PartyClose has this comment above it:
```
# End a party, kicking all party members and closing it. (this is both a message and a result)
```

It likely has this erroneous `_init()` in order to support being both a "message" and a "result". Not sure what the best solution is.

**Comment by jasonwinterpixel** [comment]
I think making `PartyCloseSend` in NakamaRTMessage and then changing the `_init()` in PartyClose is a solution here.

ie:
`NakamaRTMessage`
```
# End a party, kicking all party members and closing it.
class PartyCloseSend extends NakamaAsyncResult:
	const _SCHEMA = {
		"party_id": {"name": "party_id", "type": TYPE_STRING, "required": true},
	}
	# Party ID to close.
	var party_id : String

	func _init(p_id : String):
		party_id = p_id

	func serialize():
		return NakamaSerializer.serialize(self)

	func get_msg_key() -> String:
		return "party_close"

	func _to_string():
		return "PartyCloseSend<party_id=%s>" % [party_id]

	static func create(p_ns : GDScript, p_dict : Dictionary) -> PartyClose:
		return _safe_ret(NakamaSerializer.deserialize(p_ns, "PartyClose", p_dict), PartyClose) as PartyClose
```

`NakamaRTAPI`
```
# This party has been closed, or you've been kicked.
class PartyClose extends NakamaAsyncResult:
	const _SCHEMA = {
		"party_id": {"name": "party_id", "type": TYPE_STRING, "required": true},
	}

	var party_id : String

	func _init(p_ex = null).(p_ex):
		pass

	func serialize():
		return NakamaSerializer.serialize(self)

	func _to_string():
		if is_exception(): return get_exception()._to_string()
		return "PartyClose<party_id=%s>" % [party_id]

	static func create(p_ns : GDScript, p_dict : Dictionary) -> PartyClose:
		return _safe_ret(NakamaSerializer.deserialize(p_ns, "PartyClose", p_dict), PartyClose) as PartyClose

	static func get_result_key() -> String:
		return "party_close"
```

The differences are in the presence of `get_result_key()`, `get_msg_key()`, the signature of `_init()` and the `_to_string()`

**Comment by dsnopek** [comment]
I think we could still keep the same class used for both the message and the result, by changing the constructor and  `NakamaSocket.close_party_async()`. And I think this is desirable, because, eventually, it would be nice to automatically generate NakamaRTAPI.gd from the [realtime.proto](https://github.com/heroiclabs/nakama/blob/master/vendor/github.com/heroiclabs/nakama-common/rtapi/realtime.proto) in the Nakama source (similar to how to how we automatically generate the NakamaAPI.gd), and that only defines a single message for both sending and receiving. Whereas NakamaSocket.gd is always going to be hand-written, similar to NakamaClient.gd.

I've created PR #105 that attempts this!

Can you try the PR and let me know if this works in your game?

**Comment by dsnopek** [comment]
@jasonwinterpixel When you have a chance, could you please let me know if PR #105 works for you? Thanks!

**Comment by jasonwinterpixel** [comment]
Yes. https://github.com/heroiclabs/nakama-godot/pull/105 works. Thanks!
