### ISSUE TITLE
Nakama Server Disconnection Issue with Fifth Player in Godot Engine Game

### ISSUE THREAD

**Issue by jo-jordan** [heroiclabs/nakama-godot#181]
Hello,

We are currently developing an online multiplayer game using the Godot engine in conjunction with Nakama-Godot. Our game includes matches (rooms) with a maximum player capacity of eight.

However, we're encountering an issue. While the game functions perfectly fine when four players join a match, difficulties arise with the fifth player's attempt to join. Specifically, the previously connected players tend to experience disconnection issues with the Nakama server.

How we use:
```
var SOCKET: NakamaSocket
# init...

# create match
SOCKET.create_match_async()

# other player join match
SOCKET.join_match_async(match_id)
```

It's worth noting that we've kept all configurations in the Nakama server at their default settings. Furthermore, our test server — running the Nakama server — boasts specs of 2 cores and 4GB, with sufficient bandwidth.

We appreciate any assistance you can provide in this matter. Thank you.

**Comment by mofirouz** [comment]
This is a question best asked on the forum. Please include more details on what the problem is and what kind of Nakama interaction happens from the client, what errors (if any) is seen, and if you have any server side custom code as well - also Nakama server logs and version would be helpful too alongside client version number. Thanks! 

https://forum.heroiclabs.com
