### ISSUE TITLE
Why is `ApiAccount.wallet` a String instead of a Dictionary?

### ISSUE THREAD

**Issue by hunterloftis** [heroiclabs/nakama-godot#77]
Relevant line: https://github.com/heroiclabs/nakama-godot/blob/522f01fd4dea8b72ed66bfbe994cb623159c4595/addons/com.heroiclabs.nakama/api/NakamaAPI.gd#L213

This is pretty confusing, especially since an empty wallet string that looks like a Dictionary ("{}") is returned alongside the actual user Dictionary in the same `ApiAccount` object.

**Comment by novabyte** [comment]
@hunterloftis The wallet is returned as an escaped JSON string type because its not possible to represent unstructured data in a Protocol Buffers API which is what the REST gateway is translated into with the game server:

https://github.com/heroiclabs/nakama-common/blob/master/api/api.proto#L33-L49

I guess it could be useful to have a utility function that can decode the wallet into the respective type in your project code. A pull request would be welcome 🙏

**Comment by hunterloftis** [comment]
Instead of a utility function to decode a JSON string into a type, would it not be simpler to expose `wallet` as a [JSONParseResult](https://docs.godotengine.org/en/stable/classes/class_jsonparseresult.html#class-jsonparseresult)?

That's how I'm working around this as a consumer right now. Happy to make a PR to bring it into the library itself if that approach sounds reasonable to you.

**Comment by novabyte** [comment]
@Faless What do you think? It could be useful to handle the decode logic for developers into a `JSONParseResult`.

**Comment by Faless** [comment]
If the wallet is guaranteed to be a Dictionary, it could be made into a Dictionary.
`JSONParseResult` is the structured return type of json parsing, so it's not better then the String per se if you don't know the type, since it might contain a string, an array, a dictionary, etc.
Accessing the wallet via `account.wallet.result` is not much better the accessing it via `parse_json(account.wallet)` to be honest.

What is non-trivial would be making an exception for ApiAccount.wallet specifically since the swagger API defines it as a String.
In fact, the [dotnet API](https://github.com/heroiclabs/nakama-dotnet/blob/master/src/Nakama/ApiClient.gen.cs#L328) also treat that field as String.

**Comment by Faless** [comment]
> What is non-trivial would be making an exception for ApiAccount.wallet

I mean, it's probably not too bad, just likely quite hacky

**Comment by hunterloftis** [comment]
> If the wallet is guaranteed to be a Dictionary, it could be made into a Dictionary.

Agreed, if it's guaranteed to be a Dictionary then that's how it should ideally be presented to the user. (that was how I assumed it was being presented, until I realized it was the string "{}" rather than a Dictionary).

The workaround is straightforward, but first you have to hit the issue & realize what's happening:

```gdscript
var wallet = JSON.parse(account.wallet).result
```

**Comment by Faless** [comment]
> The workaround is straightforward, but first you have to hit the issue & realize what's happening

Yeah, I totally realize what you are saying, what I meant is that those classes are auto-generated from a specification which is not under the control of this repository and that specification defines that field as a String.
So treating that specific field differently from the other strings is going to be hacky (although again, possible).

**Comment by novabyte** [comment]
@Faless I'm not super familiar with GDScript as a language. Does it support the option to write extension methods (like in C#)? That way we could leave the code generated records but define a util method on the record types in their own file.

**Comment by Faless** [comment]
> Does it support the option to write extension methods (like in C#)?

Sadly no, there have been discussions about it, but it's not planned yet.
Maybe we can have the codegen add utility methods in a generic way without making a mess. I'll look into it.

**Comment by Faless** [comment]
@novabyte see my proposal in #77
